apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncwave-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HolyBitsLLC/argocd-bootstrap-demo.git
    targetRevision: master
    path: syncwave-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
